### ISSUE TITLE
Clicking Run simulation multiple times causes download csv to append

### ISSUE THREAD

**Issue by seanfreiburg** [boknows/cFIREsim-open#12]
Problem: Clicking Run simulation multiple times causes "download csv" to append to the last "download csv" which looks like this "download CSVdownload CSVdownload CSVdownload CSVdownload CSV"
http://i.imgur.com/tw7nvgV.png

Expected behavior: The "download csv" to be replaced by the newest, or to append on with a new line.

**Comment by boknows** [comment]
This was fixed in a recent commit.  Please refresh the page a couple of times and try again.  I could not reproduce this anymore.

**Comment by seanfreiburg** [comment]
Yep, it's fixed.
