### ISSUE TITLE
Spending Floor/Ceiling not functioning

### ISSUE THREAD

**Issue by boknows** [boknows/cFIREsim-open#16]
Repeatable using the Percent of Portfolio spending plan. It appears that the spending floor is not being used.

**Comment by jchristian** [comment]
Have you looked at pull request https://github.com/boknows/cFIREsim-open/pull/15?  It should fix this issue along with a few others found with the percent of portfolio spending plan.

**Comment by boknows** [comment]
Huh, I thought that I merged that pull request to the main branch.  I'll review tonight, thanks.
