### ISSUE TITLE
Percent of Portfolio missing ceiling/floor options

### ISSUE THREAD

**Issue by boknows** [boknows/cFIREsim-open#18]
I completely missed this until someone reviewed it.  The Percent of Portfolio spending method should always have a floor/ceiling available, not just if you change the "percentage type". 

I believe that the dropdowns in the form should be reworked to be closer to the legacy code, and the spending method itself needs to be adjusted to accept floor/ceiling for this whole spending method.  I'm guessing that taking about "percentage type" altogether would be the best path.

**Comment by jchristian** [comment]
Are you thinking the "percentage type" field should just be removed and have the floor/ceiling options merged from both types?  So for the floor have the options:
- No Floor
- Pensions/SS
- Defined Value (Inflation Adjusted)
- As a Percentage of Portfolio
- Percentage of Previous Year

And ceiling would have the options:
- No Ceiling
- Defined Value (Inflation Adjusted)
- As a Percentage of Portfolio

**Comment by boknows** [comment]
I think that is exactly what needs to happen. Because the standard percent
of portfolio method goes up and down and could use floor and ceiling.
