### ISSUE TITLE
Implement "tabs" for output graphs

### ISSUE THREAD

**Issue by boknows** [boknows/cFIREsim-open#20]
In the legacy cFIREsim, every new simulation creates a new browser tab.  This allows for easy comparison between multiple similar simulations.  With the new javascript code, I believe that it is inconveinient to open a new tab and pass along the data, which is why I opted for a pop-up window.  However, this makes it hard to compare simulations, because you can't easily open multiple simulations at once.

We either need to implement some psuedo-tabs in the output pop-up, or re-implement the legacy version by sending the data to a new tab.

**Comment by jchristian** [comment]
I know there is quite a bit of information, but would it be possible to pass the simulation parameters through the URL?  Would make this request fairly trivial and allow easy saving of simulations.

**Comment by boknows** [comment]
I'm pretty close to implementing pseudo tabs inside a modal pop-up, so this
will be moot soon.

**Comment by boknows** [comment]
Added in https://github.com/boknows/cFIREsim-open/commit/5b1541e2e07db1dc60dc919894e0880f19555ad1
