### ISSUE TITLE
When using the Hebeler Autopilot method, portfolio graph has "Spending" as the label when hovering a point.

### ISSUE THREAD

**Issue by bogosj** [boknows/cFIREsim-open#40]
When using the Hebeler Autopilot method, portfolio graph has "Spending" as the label when hovering a point.

![image](https://cloud.githubusercontent.com/assets/10186620/9567178/929a6d40-4eef-11e5-8589-7547b22a3791.png)

**Comment by boknows** [comment]
Thanks for reporting. Fixed in https://github.com/boknows/cFIREsim-open/commit/c7675ab088c10faeb74d5ae449405633db9a5d6b and updated the website.

**Comment by boknows** [comment]
By the way, I'm psyched that the first bug reported was an easy labelling issue. lol
