### ISSUE TITLE
VPW Spending Method shoots past zero

### ISSUE THREAD

**Issue by boknows** [boknows/cFIREsim-open#52]
If there is a defined spending floor present, some of the VPW cycles will run past $0 in portfolio.  VPW, by definition, tries to hit $0 exactly.

**Comment by jchristian** [comment]
What's the expected result?  If the spending floor is greater than the portfolio value, we should cap the spending for the year to the portfolio value?

**Comment by boknows** [comment]
I actually didn't check close enough, and now I'm on mobile. Does it ONLY
go negative in the final year? By its definition, VPW should be exactly
zero in the last year. I'm actually not sure the expected result if
spending is higher. I would think it was designed to never happen, but that
might not take floors and ceilings into account.

What's the expected result? If the spending floor is greater than the
portfolio value, we should cap the spending for the year to the portfolio
value?

—
Reply to this email directly or view it on GitHub
<https://github.com/boknows/cFIREsim-open/issues/52#issuecomment-142108480>.

**Comment by jchristian** [comment]
It is going negative on more than the final year.  Not too surprising if you consider an extreme case, such as setting the floor to something like double the initial portfolio value.

I think capping the floor to the portfolio value is the way to go.  It will still cause some scenarios to draw down to zero before the end of retirement, though.

**Comment by boknows** [comment]
Well, if it goes to zero before the end, we need a way of expressing that,
since I believe the intention of VPW was to never "fail".

**Comment by jchristian** [comment]
Well, the graphs do a pretty good job of expressing it.  If it goes to zero early, the spending flat-lines at zero which is pretty obvious.  It should probably be a cycle failure, though, which it isn't currently (since cycle failures are "< 0" and it only goes to 0).  What did you have in mind?

**Comment by jchristian** [comment]
The pull request keeps portfolio from going negative, but doesn't add any new way to express a portfolio cycle that fails to the user.
