### ISSUE TITLE
Spending Floor not activating in first 5 years of CAPE spending method

### ISSUE THREAD

**Issue by boknows** [boknows/cFIREsim-open#55]
Test case: Default values for all. Select CAPE spending. Change CAPE modifier to 0.6.  Set Defined Spending Floor of $35000. 

You'll see that in the first 5 years of a few simulation cycles that the spending gets below $35000. I think it's only happening in the data used in the 1800s, which indicates that there is an issue when the CAPE data is missing (those first 10 years?).

**Comment by boknows** [comment]
It might not be limited to the first few years.  This is me adding the CAPE method to my base retirement scenario: http://www.cfiresim.com/dev/input.php?id=215    A couple of times in the middle/end thirds, spending drops below the spending floor.

**Comment by boknows** [comment]
The return function for the CAPE method isn't consistent with the other variable spending methods, in that if the portfolio goes south, the CAPE spending goes south too.  We should probably stay consistent with the weird "you can go into negative portfolio" thing that cFIREsim keeps persisting. 

I'm logging off of coding for the night. If you can, look it over, if not I'll get it tomorrow,

**Comment by jchristian** [comment]
Yeah, this will happen with any spending method using a basic spending
floor.  They all use the same logic to determine their floor, which doesn't
allow it to go negative.  The change was made to keep the vpw method from
drawing down past zero.

Should only the vpw method have this special, "can't go negative logic"?
Would be a simple change.

**Comment by boknows** [comment]
I suppose that VPW should be the only one, because the entire premise of VPW is to arrive exactly at zero at the end of the last year (which isn't realistic because you obviously can't predict when you're going to die, but I digress).
