### ISSUE TITLE
Add  a Spending Plan option for RMD - enhancement request

### ISSUE THREAD

**Issue by mouchma** [boknows/cFIREsim-open#60]
It would be great if there was a spending plan based solely on RMD.  This is one of the drawdown options I am considering and would love to be able to model it and compare the output to other drawdown methods.  Thank you.

**Comment by boknows** [comment]
Marilyn, 

Technically this already exists.  If you choose the "Hebeler Autopilot" method, it is comprised of a blend between the 4% rule (labeled CPI) and the RMD method.  To make this purely a RMD method, you'd simply change the "Weighted RMD" field to 100, and the "Weighted CPI" field to 0.

I'm going to close this issue, as it is somewhat redundant.

**Comment by mouchma** [comment]
Thank you.
